name: dice_wise
version: 1.0.0+1
publish_to: none
description: Dice game with google sign in.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  bot_toast: ^4.0.1
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  google_sign_in: ^5.2.4

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/